apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: thanu-ns1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-cont
        image: mysql
        ports:
          - containerPort: 3306
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"

        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MYSQL_ROOT_PASSWORD
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PASSWORD

        volumeMounts:
        - name: dumysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: dumysql-storage
        persistentVolumeClaim:
            claimName: dudynamic-pvc    


---
apiVersion: v1
kind: Service
metadata:
  name: dumysql-svc
  namespace: thanu-ns1
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP    