apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: thanu-ns1
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Root@123"
  MYSQLDB_USER: "college_user"
  MYSQLDB_PASSWORD: "deereddy@123"
  


    