apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thanu-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods","nodes",namespaces]
  verbs: ["get", "list", "watch","patch","delete","update"]