apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thanu-rolebinding
  namespace: thanu-ns1
subjects:
- kind: User
  name: raj
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: thanu-sa
  namespace: thanu-ns1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: thanu-role
  apiGroup: rbac.authorization.k8s.io
